### ISSUE TITLE
MIoU not properly reported at ensembles

### ISSUE THREAD

**Issue by AntreasAntoniou** [AntreasAntoniou/GATE#22]
**Describe the bug**
MIoU is NaN in ensembles

**To Reproduce**
```bash
alpha-ade20k-SIGLIP-P16-224-7: accelerate launch --mixed_precision=bf16 gate/run.py exp_name=alpha-ade20k-SIGLIP-P16-224-7 encoder=timm encoder.image_size=224 encoder.pretrained=True encoder.timm_model_name=vit_base_patch16_siglip_224 encoder.clip_model_name=openai/clip-vit-base-patch16  adapter=segmentation-adapter adapter.loss_type_id=default  dataset=ade20k optimizer.lr=6e-06 optimizer.weight_decay=0.01 trainer=image_semantic_segmentation evaluator=image_semantic_segmentation num_workers=32 seed=7 train_batch_size=8 eval_batch_size=8 train_iters=10000 learner.evaluate_every_n_steps=500
```

**Expected behavior**
MIoU should be properly computed

**Screenshots**
```bash
/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/transformers/models/bart/modeling_bart.py:755: FutureWarning: The class `PretrainedBartModel` has been depreciated, please use `BartPreTrainedModel` instead.
  warnings.warn(
wandb: Currently logged in as: evolvingfungus (machinelearningbrewery). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.16.0
wandb: Run data is saved locally in /disk/scratch_fast1/aantoni2/GATE/wandb/run-20231201_235449-8a10k19m
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run clean-puddle-201
wandb: ⭐️ View project at https://wandb.ai/machinelearningbrewery/gate-dev-0-9-1
wandb: 🚀 View run at https://wandb.ai/machinelearningbrewery/gate-dev-0-9-1/runs/8a10k19m
/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(

wandb: 
wandb: Run history:
wandb:                                         global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:                                model/num_parameters ▁
wandb:    testing/ensemble_1/background_ce_loss-epoch-mean ▁▁
wandb:     testing/ensemble_1/background_ce_loss-epoch-std ▁▁
wandb:  testing/ensemble_1/background_dice_loss-epoch-mean ▁▁
wandb:   testing/ensemble_1/background_dice_loss-epoch-std ▁▁
wandb: testing/ensemble_1/background_focal_loss-epoch-mean ▁▁
wandb:  testing/ensemble_1/background_focal_loss-epoch-std ▁▁
wandb:       testing/ensemble_1/background_loss-epoch-mean ▁▁
wandb:        testing/ensemble_1/background_loss-epoch-std ▁▁
wandb:               testing/ensemble_1/ce_loss-epoch-mean ▁▁
wandb:                testing/ensemble_1/ce_loss-epoch-std ▁▁
wandb:             testing/ensemble_1/dice_loss-epoch-mean ▁▁
wandb:              testing/ensemble_1/dice_loss-epoch-std ▁▁
wandb:            testing/ensemble_1/focal_loss-epoch-mean ▁▁
wandb:             testing/ensemble_1/focal_loss-epoch-std ▁▁
wandb:                  testing/ensemble_1/loss-epoch-mean ▁▁
wandb:                   testing/ensemble_1/loss-epoch-std ▁▁
wandb:                 testing/ensemble_1/overall_accuracy ▁
wandb:    testing/ensemble_3/background_ce_loss-epoch-mean ▁▁
wandb:     testing/ensemble_3/background_ce_loss-epoch-std ▁▁
wandb:  testing/ensemble_3/background_dice_loss-epoch-mean ▁▁
wandb:   testing/ensemble_3/background_dice_loss-epoch-std ▁▁
wandb: testing/ensemble_3/background_focal_loss-epoch-mean ▁▁
wandb:  testing/ensemble_3/background_focal_loss-epoch-std ▁▁
wandb:       testing/ensemble_3/background_loss-epoch-mean ▁▁
wandb:        testing/ensemble_3/background_loss-epoch-std ▁▁
wandb:               testing/ensemble_3/ce_loss-epoch-mean ▁▁
wandb:                testing/ensemble_3/ce_loss-epoch-std ▁▁
wandb:             testing/ensemble_3/dice_loss-epoch-mean ▁▁
wandb:              testing/ensemble_3/dice_loss-epoch-std ▁▁
wandb:            testing/ensemble_3/focal_loss-epoch-mean ▁▁
wandb:             testing/ensemble_3/focal_loss-epoch-std ▁▁
wandb:                  testing/ensemble_3/loss-epoch-mean ▁▁
wandb:                   testing/ensemble_3/loss-epoch-std ▁▁
wandb:                 testing/ensemble_3/overall_accuracy ▁
wandb:                         training/background_ce_loss ▅█▂▆▂▄▂▄▁▂▁▂▂▄▅▃▄▃▂▄▅▄▇█▃▂▂▆▄▃▅▆▁▃▆▄▂▄▃▆
wandb:                       training/background_dice_loss ▄▇▂▃▄▂▂▂▄▃▂▃▄▆▂▃▃▄▂▂▃▃▂▄▂▃▂█▂▂▃▅▄▂▃▄▃▄▂▁
wandb:                      training/background_focal_loss ▅█▂▆▂▄▃▄▁▁▂▃▃▄▅▂▄▃▂▄▅▄▇█▄▁▁▅▄▄▅▆▁▃▆▄▃▄▃▆
wandb:                            training/background_loss ▅█▂▆▂▄▃▄▁▂▁▂▂▄▅▃▄▃▂▄▅▄▇█▃▂▂▆▄▃▅▆▁▃▆▄▃▄▃▆
wandb:                                 training/bprop_time █▁▁▁▁▁▁▁█▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▁
wandb:                                    training/ce_loss ▆▅▂▆▃▅▄▃▂▂▂▃▁▄▅▂▃▂▅▂▃▄▅▆▄▁▁▅▂█▂▅▆▅▄▃▅▄▁▆
wandb:                                  training/dice_loss ▄▇▂▃▄▂▂▂▄▃▂▃▄▆▂▃▃▅▂▂▃▃▂▄▂▃▂█▂▃▃▅▄▂▃▄▃▄▂▁
wandb:                                 training/focal_loss ▅▅▂▆▃▅▄▃▂▂▂▄▂▃▄▂▃▂▄▂▃▄▄▆▄▁▁▄▂█▂▄▅▅▃▂▅▄▁▅
wandb:                                 training/fprop_time █▂▂▁▂▂▂▂▆▁▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▁▂▂▂▂▂▂▂▂▁▂▂▂▂▂
wandb:                                       training/loss ▆▅▂▇▃▅▄▃▂▂▂▃▁▄▅▂▃▂▅▂▃▄▅▇▄▁▁▅▂█▂▅▅▅▄▃▅▄▁▆
wandb:                                         training/lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            validation/background_ce_loss-epoch-mean ▁▁
wandb:             validation/background_ce_loss-epoch-std ▁▁
wandb:          validation/background_dice_loss-epoch-mean ▁▁
wandb:           validation/background_dice_loss-epoch-std ▁▁
wandb:         validation/background_focal_loss-epoch-mean ▁▁
wandb:          validation/background_focal_loss-epoch-std ▁▁
wandb:               validation/background_loss-epoch-mean ▁▁
wandb:                validation/background_loss-epoch-std ▁▁
wandb:                       validation/ce_loss-epoch-mean ▁▁
wandb:                        validation/ce_loss-epoch-std ▁▁
wandb:                     validation/dice_loss-epoch-mean ▁▁
wandb:                      validation/dice_loss-epoch-std ▁▁
wandb:                    validation/focal_loss-epoch-mean ▁▁
wandb:                     validation/focal_loss-epoch-std ▁▁
wandb:                          validation/loss-epoch-mean ▁▁
wandb:                           validation/loss-epoch-std ▁▁
wandb:                                     validation/mIoU ▁
wandb:                            validation/mean_accuracy ▁
wandb:                         validation/overall_accuracy ▁
wandb: 
wandb: Run summary:
wandb:                                         global_step 10000
wandb:                                model/num_parameters 349639319
wandb:    testing/ensemble_1/background_ce_loss-epoch-mean 1.37157
wandb:     testing/ensemble_1/background_ce_loss-epoch-std 0.18978
wandb:  testing/ensemble_1/background_dice_loss-epoch-mean 0.69328
wandb:   testing/ensemble_1/background_dice_loss-epoch-std 0.01147
wandb: testing/ensemble_1/background_focal_loss-epoch-mean 0.24148
wandb:  testing/ensemble_1/background_focal_loss-epoch-std 0.04643
wandb:       testing/ensemble_1/background_loss-epoch-mean 1.61305
wandb:        testing/ensemble_1/background_loss-epoch-std 0.23586
wandb:               testing/ensemble_1/ce_loss-epoch-mean 1.56341
wandb:                testing/ensemble_1/ce_loss-epoch-std 0.36976
wandb:             testing/ensemble_1/dice_loss-epoch-mean 0.69663
wandb:              testing/ensemble_1/dice_loss-epoch-std 0.01147
wandb:            testing/ensemble_1/focal_loss-epoch-mean 0.30386
wandb:             testing/ensemble_1/focal_loss-epoch-std 0.09362
wandb:                  testing/ensemble_1/loss-epoch-mean 2.02857
wandb:                   testing/ensemble_1/loss-epoch-std 0.4718
wandb:                             testing/ensemble_1/mIoU nan
wandb:                    testing/ensemble_1/mean_accuracy nan
wandb:                 testing/ensemble_1/overall_accuracy 0.0
wandb:    testing/ensemble_3/background_ce_loss-epoch-mean 1.39623
wandb:     testing/ensemble_3/background_ce_loss-epoch-std 0.19077
wandb:  testing/ensemble_3/background_dice_loss-epoch-mean 0.69405
wandb:   testing/ensemble_3/background_dice_loss-epoch-std 0.01155
wandb: testing/ensemble_3/background_focal_loss-epoch-mean 0.24716
wandb:  testing/ensemble_3/background_focal_loss-epoch-std 0.04706
wandb:       testing/ensemble_3/background_loss-epoch-mean 1.64339
wandb:        testing/ensemble_3/background_loss-epoch-std 0.2375
wandb:               testing/ensemble_3/ce_loss-epoch-mean 1.55858
wandb:                testing/ensemble_3/ce_loss-epoch-std 0.36999
wandb:             testing/ensemble_3/dice_loss-epoch-mean 0.69733
wandb:              testing/ensemble_3/dice_loss-epoch-std 0.01156
wandb:            testing/ensemble_3/focal_loss-epoch-mean 0.30295
wandb:             testing/ensemble_3/focal_loss-epoch-std 0.09361
wandb:                  testing/ensemble_3/loss-epoch-mean 2.02587
wandb:                   testing/ensemble_3/loss-epoch-std 0.47207
wandb:                             testing/ensemble_3/mIoU nan
wandb:                    testing/ensemble_3/mean_accuracy nan
wandb:                 testing/ensemble_3/overall_accuracy 0.0
wandb:                         training/background_ce_loss 1.02779
wandb:                       training/background_dice_loss 0.66912
wandb:                      training/background_focal_loss 0.17874
wandb:                            training/background_loss 1.20653
wandb:                                 training/bprop_time 0.03071
wandb:                                    training/ce_loss 1.43193
wandb:                                  training/dice_loss 0.67313
wandb:                                 training/focal_loss 0.25909
wandb:                                 training/fprop_time 0.11533
wandb:                                       training/loss 1.81167
wandb:                                         training/lr 0.0
wandb:            validation/background_ce_loss-epoch-mean 1.36121
wandb:             validation/background_ce_loss-epoch-std 0.19231
wandb:          validation/background_dice_loss-epoch-mean 0.69493
wandb:           validation/background_dice_loss-epoch-std 0.0138
wandb:         validation/background_focal_loss-epoch-mean 0.23839
wandb:          validation/background_focal_loss-epoch-std 0.04665
wandb:               validation/background_loss-epoch-mean 1.5996
wandb:                validation/background_loss-epoch-std 0.23863
wandb:                       validation/ce_loss-epoch-mean 1.53148
wandb:                        validation/ce_loss-epoch-std 0.37269
wandb:                     validation/dice_loss-epoch-mean 0.69829
wandb:                      validation/dice_loss-epoch-std 0.01381
wandb:                    validation/focal_loss-epoch-mean 0.29462
wandb:                     validation/focal_loss-epoch-std 0.09379
wandb:                          validation/loss-epoch-mean 1.98606
wandb:                           validation/loss-epoch-std 0.47918
wandb:                                     validation/mIoU 27.62092
wandb:                            validation/mean_accuracy 36.35272
wandb:                         validation/overall_accuracy 63.85703
wandb: 
wandb: 🚀 View run clean-puddle-201 at: https://wandb.ai/machinelearningbrewery/gate-dev-0-9-1/runs/8a10k19m
wandb: ️⚡ View job at https://wandb.ai/machinelearningbrewery/gate-dev-0-9-1/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjEyMDA3Mjg1Ng==/version_details/v10
wandb: Synced 7 W&B file(s), 187 media file(s), 3 artifact file(s) and 1 other file(s)
wandb: Find logs at: ./wandb/run-20231201_235449-8a10k19m/logs
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread IntMsgThr:
    self.run()
Traceback (most recent call last):
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/threading.py", line 953, in run
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/threading.py", line 953, in run
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 286, in check_stop_status
    self._target(*self._args, **self._kwargs)
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 300, in check_internal_messages
    self._loop_check_status(
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
    self._loop_check_status(
    local_handle = request()
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 224, in _loop_check_status
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 750, in deliver_stop_status
    local_handle = request()
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 766, in deliver_internal_messages
    return self._deliver_stop_status(status)
    return self._deliver_internal_messages(internal_message)
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 468, in _deliver_stop_status
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 490, in _deliver_internal_messages
    return self._deliver_record(record)
    return self._deliver_record(record)
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 437, in _deliver_record
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 437, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
    handle = mailbox._deliver_record(record, interface=self)
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    interface._publish(record)
    interface._publish(record)
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
    self._sock_client.send_record_publish(record)
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
    self.send_server_request(server_req)
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._send_message(msg)
    self._sendall_with_error_handle(header + data)
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    self._sendall_with_error_handle(header + data)
  File "/disk/scratch_fast1/aantoni2/mambaforge/envs/gate/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AntreasAntoniou** [comment]
Fixed in https://github.com/AntreasAntoniou/GATE/commit/6ab7ec4c4ed59d2c4ea575e1a0a532854e489f28
